### ISSUE TITLE
[Bug] Missing chord formulas

### ISSUE THREAD

**Issue by michaldivis** [michaldivis/dark-music-concepts#12]
Some common 7th chords from musical theory are missing in library. For example Augmented 7th (C E G# B).

@KoHHeKT please add a list of the missing chord formulas when you have the time. Thanks!

**Comment by KoHHeKT** [comment]
Basic formula for seventh chord is "Triad + Seventh Interval From Root"
Possible triads: Major, Minor, Augmented, Diminished
Possible Seventh Intervals: Major, Minor, Diminished


Triad | Seventh | SeventhChord | Comment
-- | -- | -- | --
Maj | Maj | MM7 |  
Maj | Min | Mm7 |  
Maj | Dim | - | not used at all, it is enharmonically equal to Major(add6) chord
Min | Maj | mM7 | rare
Min | Min | mm7 |  
Min | Dim | - |  not used at all, it is enharmonically equal to minor(add6) chord
Dim | Maj | dM7 | can't remember any examples
Dim | Min | dm7 |  
Dim | Dim | dd7 |  
Aug | Maj | AM7 | very rare
Aug | Min | Am7 | can't remember any examples
Aug | Dim | - | not used at all, it is enharmonically equal to 1st inversion of

The next step is to find correspondence of this chords with chords in the code

**Comment by michaldivis** [comment]
Will be considered in v1.0.
