### ISSUE TITLE
Do you need contributors?

### ISSUE THREAD

**Issue by KoHHeKT** [michaldivis/dark-music-concepts#8]
Hi!
I was looking for C# music theory libs for my pet project(yet another ear training app). I've found that this project is quite nice.

Do you need any help? I can contribute since I have some industry experience with .NET, also I'm capable to help with music theory area since I have a college degree in music(choir conducting and music theory).

Now I'm going to try your lib in my app and probably give some feedback.

Thanks for your project!
Feel free to contact me on telegram @KoHHeKT

**Comment by michaldivis** [comment]
Hi there, 

I'd love that! The more you can help the better. I've crafted this library to fit the needs of my own project, so it would benefit greatly from an outside perspective.

Also, the little bit of music theory I know is self thaught, I'd love your help on that side, too.

I'll be grateful for any feedback or help, thanks!

**Comment by KoHHeKT** [comment]
Do you have any ideas for the first task?

Usually I prefer to write some tests for to get deeper understanding of the project. If you have any code that needs more tests I wish start from there?

**Comment by michaldivis** [comment]
One thing that comes to mind is the Invert method on the Chord class. Is that a good starting point?
